### ISSUE TITLE
Naive question about biological background differences 

### ISSUE THREAD

**Issue by newbieMars** [kharchenkolab/gpsFISH#21]
Hi,

First of all, thanks for this great tool! 

I have a naive question. Suppose I have a paired scRNAseq and targeted spatial transcriptomics ((for example: Xenium) dataset from a given tissue and biological context (for example: mouse brain data) and I want to design a gene panel gene for a new targeted spatial transcriptomics experiment on the same platform (i.e: Xenium) but from a different tissue and biological context (for example: human lymph node scRNAseq dataset). Will the parameters inferred from my mouse brain paired data be suitable for designing my new gene panel despite the biological differences?

Thanks

**Comment by YidaZhang0628** [comment]
Hi,

That is a great question! Ideally, because the platform effect is learned from paired scRNA-seq and spatial data in the same biological context, it should reflect pure technical differences and this technical difference is generally thought to be the same across biological contexts as long as the technologies are the same. However, if the technology itself has varied performance across biological contexts, then the platform effect can be different across biological contexts. We always wanted to check this but when we were working on the paper, there was not much data from the same pair of platforms but under different biological contexts. With that being said, I don't have a definitive answer to your question. My hunch is that you should be ok to use the parameters inferred from one biological context for designing your new gene panel in a different biological context as long as the single-cell and spatial technologies are the same.

The bottom line is that, if you have Xenium data and scRNA-seq data from your target tissue, e.g., human lymph node, you will be better off using gpsFISH to estimate the platform effect in human lymph node first and then use the estimated parameters for gene panel selection. But since you asked this question, I assume you don't have paired data in your target tissue. In this situation, using the parameters estimated from the same pair of platforms but from a different biological context is probably the best option. Once you generate your Xenium data in your target tissue, you can then come back and estimate the platform effect using gpsFISH and check how much it deviates from the parameters estimated from the initial tissue, e.g., mouse brain. If the parameters differ a lot from each other, you can use the new one estimated in your target tissue to design new gene panels. Unfortunately, these things do take several iterations of effort.  

Hope this answers your question!
